check on linters
leonard33/consert-website pull request #1
Opened 2022-04-14 16:33 UTC by leonard33

checking linters pass

2022-04-14 20:33 UTC, VICTOR-CHUKWU requested changes
Hi @leonard33 , 

## STATUS: REQUIRED CHANGES

✔️  You did a wonderful job on this project 👏 

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-14 20:33 UTC, VICTOR-CHUKWU commented on README.md
> +## Acknowledgments
- [ ] Your README should contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design], Kindly add that

2022-04-14 20:33 UTC, VICTOR-CHUKWU commented on README.md
> +## Live Demo (not available)
- [ ] Kindly add a live website for this project hosted with github

2022-04-14 20:33 UTC, VICTOR-CHUKWU commented on README.md
> +## Live Demo (not available)
- [ ] There should be a  video of a maximum length of  5 minutes. describing the features of your project, Kindly add that

2022-04-14 20:33 UTC, VICTOR-CHUKWU commented on about.html
> +            </div>
- [ ] Kindly align these items to the center as it is on your home page to give your project uniformity
     👇 
          
![image](https://user-images.githubusercontent.com/66097371/163470287-17211ea1-cb1b-4575-a24a-141f9b779723.png)

2022-04-15 02:01 UTC, leonard33 commented
-Acknowledging Cindy Shin
- webpage deploy link added in readme file (live demo view)
- Live demo video link describing the project added in readme file
- Alligned partners section inline done

2022-04-15 02:11 UTC, leonard33 commented
- Acknowledging Cindy Shin
- webpage deploy link added in readme file (live demo view)
- Live demo video link describing the project added in readme file
- Alligned partners section inline done

2022-04-15 02:31 UTC, gemmen29 approved these changes
Hi @leonard33, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 02:31 UTC, gemmen29 commented on index.html
> +            <button class="read-more">MORE<i class="fa fa-angle-down"></i></button>
[OPTIONAL] Kindly make the speakers when the more button pressed appear above it not below it for a better UI experience
![image](https://user-images.githubusercontent.com/24703171/163507839-9cf473e9-f43a-41de-80da-be1dc57a4503.png)

2022-04-15 02:31 UTC, gemmen29 commented on about.html
> +        </section>
- [OPTIONAL] Kindly change the `section` tag to the `footer` tag for semantic purposes.
- [OPTIONAL] Kindly change the footer to be dark in the desktop version to match the Behance design.
![image](https://user-images.githubusercontent.com/24703171/163508173-eed924be-18f6-4f1c-a8b7-4fee646231ec.png)

2022-04-15 02:31 UTC, gemmen29 commented on about.html
> +            </div>
- [OPTIONAL] Kindly change the text color to white and increase the ` font-size ` a little bit in this part to match the Behance design. 

| Your design | Behance design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/163508466-e9f0f5c0-c098-4b48-80ce-26279fed14f6.png) | ![image](https://user-images.githubusercontent.com/24703171/163508498-a06afaaf-82a9-40f7-bf1e-c1ab9f97f3ae.png) |

2022-04-15 02:48 UTC, merged